zones:
  - zone_id: border-zone-1
    camera_id: camera-1
    polygon:
      - [534, 0]     # top-left
      - [764, 0]   # bottom-left
      - [760, 429]   # bottom-right
      - [531, 428]     # top-right
    sensitivity: medium

  - zone_id: border-zone-2
    camera_id: camera-zone-face
    polygon:
      - [64, 2]     # top-left
      - [764, 1]   # bottom-left
      - [765, 427]   # bottom-right
      - [73, 429]     # top-right
    sensitivity: medium


  - zone_id: border-zone-3
    camera_id: camera-loitering-copy
    polygon:
      - [2, 3]
      - [764, 3]
      - [765, 429]
      - [3, 429]
    sensitivity: medium

