zones:
  - zone_id: border-zone-1
    camera_id: camera-1
    polygon:
      - [534, 0]     # top-left
      - [764, 0]   # bottom-left
      - [760, 429]   # bottom-right
      - [531, 428]     # top-right
    sensitivity: medium
    sensitive: true
    loiter_threshold_seconds: 15
    moving_speed_threshold: 5
    dwell_threshold_seconds: 15
